### PR TITLE
54 UI fix

### PR DESCRIPTION
**Pull request by asb43**

### CODE REVIEW

**Comment by asb43** [comment]
I've tried puushing my newest changes but due to some issue I cant actually push anything to 54 anymore so I'll have to just move on to making the changes in the next sprint

**Review by AndrealHarrison — CHANGES_REQUESTED** [review]
The branch wouldn't build when I tried to run it.  Maybe something got messed up while resolving conflicts?

**Review by shahinnezam — DISMISSED** [review]
Looks good! I ran it and see the updated constraints, but didn't notice anything else- hopefully you pushed all that?

Also, the changes mentioned something about an iPad vs Retina display; don't think it matters but maybe run it on iPhone to make sure everything still looks the same as you intended? 

good job finally merging

**Comment by asb43** [comment]
> Looks good! I ran it and see the updated constraints, but didn't notice anything else- hopefully you pushed all that?
> 
> Also, the changes mentioned something about an iPad vs Retina display; don't think it matters but maybe run it on iPhone to make sure everything still looks the same as you intended?
> 
> good job finally merging

yeah the professor helped me work through getting it unclogged, I'm currently working on getting some of those old changes re-added to the project that got deleted In the  crossfire

**Comment by shahinnezam** [comment]
Photo on launch screen is now at top of screen partially cut off - try working with a different emulator, or reset the constraints on that page and start again, that usually fixes it and literally only takes 15 seconds

**Review by AndrealHarrison — CHANGES_REQUESTED** [review]
what Shahin said

**Review by AndrealHarrison — CHANGES_REQUESTED** [review]
Its looking much better but you need to fix the constraints on the switches on the profile page so they are back where they were.  you also changed the constraints on the photos in the table cell, but I'm re-doing that so I can fix that for you.  You also have several warnings on the launch screen that should be addressed. good work so far

**Comment by asb43** [comment]
All issues Andrea has mentioned are things that the professor helped me with before, The profileVC had to be changed in the manner we did it (both the switches and the Cells) in order to not have conflicts anymore, I can't revert them or else they'll just end up conflicting again. As for the Launchscreen the conflicts are a conflict between my leading and trailing constraints, due to some bs, I don't understand the text won't wrap unless I have both a leading and trailing and the image won't properly center if I mess with anything too much. Like I've said before somethings might look ugly from the storyboard/code but from the screen itself so long as it looks and functions as expected it's something that's gonna need to just be accepted for now I'll probably try to figure out a way to make a better on a later sprint but for right now that's out of scope for what I'm currently trying to work on

**Review by AndrealHarrison — APPROVED** [review]
looks good

**Review by fabricekalvanda — APPROVED** [review]
Looks good so far!

**Pull request merged**
